Customer_Name = input("Enter Customer Name: ")
Customer_Age = int(input("Enter Customer Age: "))
Product_Price = float(input("Enter The Price: "))
Items_list = list(input("Enter The Items: ").split())
Cupon_codes = set(input("Enter The Cupon Codes: ").split())
Delivery_Address = tuple(input("Enter The address: ").split())
Order_detailes = eval(input("Enter The Order Detailes: "))

print(f'Name: {Customer_Name}')
print(f'Age: {Customer_Age}')
print(f'Price: {Product_Price}')
print(f'Items: {Items_list}')
print(f'Cupons: {Cupon_codes}')
print(f'Address: {Delivery_Address}')
print(f'Order: {Order_detailes}')